name: flutter_getx
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  animations: ^2.0.11
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/img/

  fonts:
    - family: NanumMyeongio
      fonts:
        - asset: assets/font/NanumMyeongjo-Regular.ttf
          weight: 400
        - asset: assets/font/NanumMyeongjo-Bold.ttf
          weight: 700
        - asset: assets/font/NanumMyeongjo-ExtraBold.ttf
          weight: 800


